# This file was generated by GoReleaser. DO NOT EDIT.
class GolangciLint < Formula
  desc "Fast linters runner for Go."
  homepage "https://golangci.com"
  version "1.34.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/prakritichauhan07/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-darwin-amd64.tar.gz"
    sha256 "0ffaca8a205a5b5a228d4b54b0fece31532a7c3225b8e15da7b7b53546169e94"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/prakritichauhan07/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-amd64.tar.gz"
      sha256 "e5184d17d61a2eae85d04b72f429f44069aa597b68f9750a0551c91bc0d232ee"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/prakritichauhan07/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-arm64.tar.gz"
        sha256 "10a2d6023bd08c2b169599a63ef8bb49c167d2a1d6e28137f68b25d3354d8179"
      else
        url "https://github.com/prakritichauhan07/golangci-lint/releases/download/v1.34.0/golangci-lint-1.34.0-linux-armv6.tar.gz"
        sha256 "66a2cda3862f38419f687ba5db5b582bb755740e028adf9fdfe8e2199d3213e6"
      end
    end
  end

  def install
    bin.install "golangci-lint"
    output = Utils.popen_read("#{bin}/golangci-lint completion bash")
    (bash_completion/"golangci-lint").write output
    output = Utils.popen_read("#{bin}/golangci-lint completion zsh")
    (zsh_completion/"_golangci-lint").write output
    prefix.install_metafiles
  end

  test do
    system "#{bin}/golangci-lint --version"
  end
end
